*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 13:54:11 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 13:28:30
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 15be1c34f734
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/geoportal
chdir(): No such file or directory [core/uwsgi.c line 2591]
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 13:55:09 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 13:28:30
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 15be1c34f734
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x1c4ae80
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1c4ae80 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 13:57:11 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 13:56:47
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: ed280736c4e4
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0xce1e80
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xce1e80 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 13:59:35 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 13:56:47
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: ed280736c4e4
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0xadfe80
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xadfe80 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 14:00:43 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 13:56:47
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: ed280736c4e4
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0xc9fe80
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xc9fe80 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 14:17:33 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 14:17:10
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 4566a8b75f27
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x130ce80
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x130ce80 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 8|app: 0|req: 1/1] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:17:39 2017] GET /bookExpert/ => generated 72126 bytes in 42 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 9|app: 0|req: 1/2] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:31:33 2017] GET /bookExpert/ => generated 72126 bytes in 70 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 9|app: 0|req: 2/3] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:31:35 2017] GET /bookExpert/ => generated 72126 bytes in 28 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 14:32:29 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 14:17:10
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 4566a8b75f27
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0xd6d0a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
added /code/ to pythonpath.
added /code/bookExpert/ to pythonpath.
added /code/main/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xd6d0a0 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 9|app: 0|req: 1/1] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:32:32 2017] GET /bookExpert/ => generated 72199 bytes in 41 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 1|app: 0|req: 1/2] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:32:33 2017] GET /bookExpert/ => generated 72199 bytes in 40 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 1|app: 0|req: 2/3] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:32:34 2017] GET /bookExpert/ => generated 72199 bytes in 28 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 1)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 8|app: 0|req: 1/4] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:32:34 2017] GET /bookExpert/ => generated 72199 bytes in 41 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 9|app: 0|req: 2/5] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:32:34 2017] GET /bookExpert/ => generated 72199 bytes in 29 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 1)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 8|app: 0|req: 2/6] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:33:32 2017] GET /bookExpert/ => generated 72199 bytes in 28 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 14:33:42 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 14:17:10
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 4566a8b75f27
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x1a190a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
added /code/ to pythonpath.
added /code/bookExpert/ to pythonpath.
added /code/main/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1a190a0 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 9|app: 0|req: 1/1] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:33:44 2017] GET /bookExpert/ => generated 72197 bytes in 41 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 9|app: 0|req: 2/2] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:33:45 2017] GET /bookExpert/ => generated 72197 bytes in 28 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 1)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 8|app: 0|req: 1/3] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:34:08 2017] GET /bookExpert/ => generated 72197 bytes in 42 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 14:34:14 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 14:17:10
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 4566a8b75f27
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x24640a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
added /code/ to pythonpath.
added /code/bookExpert/ to pythonpath.
added /code/main/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x24640a0 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 7, cores: 2)
spawned uWSGI worker 3 (pid: 8, cores: 2)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 8|app: 0|req: 1/1] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:34:16 2017] GET /bookExpert/ => generated 72197 bytes in 42 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 8|app: 0|req: 2/2] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:34:17 2017] GET /bookExpert/ => generated 72197 bytes in 31 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 1)
Internal Server Error: /bookExpert/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/main/views.py", line 16, in index
    return render(request, 'home.html', context)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
[pid: 8|app: 0|req: 3/3] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:34:17 2017] GET /bookExpert/ => generated 72197 bytes in 28 msecs (HTTP/1.0 500) 4 headers in 129 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 14:34:33 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 14:17:10
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 4566a8b75f27
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x1c1b0a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
added /code/ to pythonpath.
added /code/bookExpert/ to pythonpath.
added /code/main/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1c1b0a0 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
[pid: 1|app: 0|req: 1/1] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:34:35 2017] GET /bookExpert/ => generated 14 bytes in 19 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 14:34:43 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 14:17:10
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 4566a8b75f27
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x21ba0a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
added /code/ to pythonpath.
added /code/bookExpert/ to pythonpath.
added /code/main/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x21ba0a0 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
[pid: 1|app: 0|req: 1/1] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:34:45 2017] GET /bookExpert/ => generated 14 bytes in 13 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 1/2] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:34:45 2017] GET /bookExpert/ => generated 14 bytes in 11 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 2/3] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:34:45 2017] GET /bookExpert/ => generated 14 bytes in 1 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 3/4] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:34:46 2017] GET /bookExpert/ => generated 14 bytes in 1 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 14:35:23 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 14:17:10
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 4566a8b75f27
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x10830a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
added /code/ to pythonpath.
added /code/bookExpert/ to pythonpath.
added /code/main/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x10830a0 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
[pid: 9|app: 0|req: 1/1] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:35:25 2017] GET /bookExpert/ => generated 14 bytes in 12 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 2/2] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:35:26 2017] GET /bookExpert/ => generated 14 bytes in 1 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 3/3] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:35:26 2017] GET /bookExpert/ => generated 14 bytes in 0 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 1/4] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:35:26 2017] GET /bookExpert/ => generated 14 bytes in 12 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 1|app: 0|req: 2/5] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:35:27 2017] GET /bookExpert/ => generated 14 bytes in 1 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 4/6] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:35:27 2017] GET /bookExpert/ => generated 14 bytes in 1 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 1)
[pid: 8|app: 0|req: 1/7] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:35:27 2017] GET /bookExpert/ => generated 14 bytes in 10 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Sat Sep 30 14:35:34 2017] ***
compiled with version: 5.4.0 20160609 on 30 September 2017 14:17:10
os: Linux-4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
nodename: 4566a8b75f27
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /code
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /code/bookExpert
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x7da0a0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 6 cores
*** Operational MODE: preforking+threaded ***
added /code/ to pythonpath.
added /code/bookExpert/ to pythonpath.
added /code/main/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7da0a0 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 8, cores: 2)
spawned uWSGI worker 3 (pid: 9, cores: 2)
[pid: 8|app: 0|req: 1/1] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:35:38 2017] GET /bookExpert/ => generated 14 bytes in 13 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 8|app: 0|req: 2/2] 172.19.0.1 () {46 vars in 698 bytes} [Sat Sep 30 14:35:53 2017] GET /bookExpert/ => generated 20 bytes in 1 msecs (HTTP/1.0 200) 3 headers in 108 bytes (1 switches on core 1)
